seed: 31
train_strategy: steps
n_epochs: 1
n_steps: 100
n_warmup_steps: 0
lr_scheduler_type: constant
num_workers: 0
train_shuffle: true
batch_size: 8
device: cuda
grad_clip_strategy: null
max_grad_norm: 1.0
max_grad_value: 1.0
gradient_accumulation_steps: 1
real_batch_size: 8
save_strategy: steps
save_dir: artifacts/checkpoints
save_steps: 100
save_epochs: 1
save_total_limit: 3
eval_strategy: steps
eval_steps: 50
eval_epochs: 1
mixed_precision: "no"
